appSettings:
  Setting1: "git prod setting"

connectionStrings:
   MyDB: "Data Source=GithubProdSQLServer;Initial Catalog=MyDB;User ID=xxxx;Password=xxxx"


client:
  Default_IMyLogService:
    address: "git_prod_endpoint"
    binding: "git_prod_binding"
    bindingConfiguration: "git_prod_bindingConfiguration"